uploads = []
generated = []

[[outputs]]
id = "PLsY_camJSaJlsjp7Oy0M"
uri = "file://artifacts/progress-journal/eyit-journal-dist.zip"
type = "unspecified"
title = "EYIT Journal — Production Build"

[[outputs]]
id = "643n2t8T3IRil-kcJhvTX"
uri = "file://eyit-journal.zip"
type = "unspecified"
title = "EYIT Development Journal — production build"
