// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/best-fit/ChipGrid.tsx": () => import("../components/mockups/best-fit/ChipGrid.tsx"),
  "./components/mockups/best-fit/Collapsible.tsx": () => import("../components/mockups/best-fit/Collapsible.tsx"),
  "./components/mockups/best-fit/TighterRows.tsx": () => import("../components/mockups/best-fit/TighterRows.tsx"),
  "./components/mockups/best-fit/TwoColumn.tsx": () => import("../components/mockups/best-fit/TwoColumn.tsx")
};
